### ISSUE TITLE
Incorrect/early detection of > in tags

### ISSUE THREAD

**Issue by akinuri** [anteprimorac/vscode-html-end-tag-labels#410] opened 2022-09-07 10:05 UTC
**Describe the bug**
In the following HTML block (Laravel, Blade), there seems to be a bug about where the end tag label is placed.

```html
<div class="form-check form-check-inline">
    <input
        class="form-check-input"
        type="radio"
        name="gender"
        id="male"
        value="male"
        @if ($user->gender == "male") checked @endif
        />
    <label class="form-check-label" for="male">Male</label>
</div>
```
For the input tag, the label is placed incorrectly. It looks like this: `@if ($user->/#male.form-check-inputgender) @endif`.

I wanted to see if this is specific only to the input tag or all elements, and it seems to be specific to the input tag.

I copied all attributes from input to the parent div, and it didn't produce the same result.

![Screenshot 2022-09-07 125551](https://user-images.githubusercontent.com/13146977/188849831-89581cf3-29a7-454b-a52e-7fccedb050a3.png)

The moment I change/rename the `div` to `input`, the same thing happens.

I'm guessing the problem is with the `>` character. The extension is thinking `->` is what it's looking for, but this is not a valid tag end character(s). It should be looking for:
* `>` (space + >)
* `">`
* `/>`

**Desktop:**
 - OS: Windows
 - VSCode Version: 1.71.0
 - Extension Version: 0.9.0

**Comment by anteprimorac** [comment] 2023-02-01 13:02
Closing this as duplicate of #271

**Closed by anteprimorac** 2023-02-01 13:02 UTC
Labels: bug, help wanted, php
