### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [anteprimorac/vscode-html-end-tag-labels#453] opened 2023-01-30 03:27 UTC
inside .Vue files, inside `<template>`... do the thing

also add the ability to specify any random extension for the extension to run in.

**Comment by anteprimorac** [comment] 2023-02-01 13:03
@SIGSTACKFAULT, thank you for the bug report. I am closing this as a duplicate of #372.

**Closed by anteprimorac** 2023-02-01 13:03 UTC
Labels: enhancement, vue
